name: Local deployment to Kind
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: 

jobs: 
  deploy-linux:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4
      - name: Helm deployment
        env:
          POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
        run: |
          helm upgrade api spring-cubix --install -f api.yaml -n cubix
          helm upgrade db spring-cubix --install -f db.yaml -n cubix --set env[2].value="$POSTGRESQL_PASSWORD"
